apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk
---
apiVersion: v1
kind: Pod
metadata:
  name: zk-0
  labels:
    app: zk
spec:
  hostname: zk-0
  subdomain: zk-hs
  containers:
  - name: zk
    image: "registry.k8s.io/kubernetes-zookeeper:1.0-3.4.10"
    ports:
    - containerPort: 2181
      name: client
    - containerPort: 2888
      name: server
    - containerPort: 3888
      name: leader-election
    command:
    - sh
    - -c
    - "start-zookeeper \
      --servers=3 \
      --data_dir=/var/lib/zookeeper/data \
      --data_log_dir=/var/lib/zookeeper/data/log \
      --conf_dir=/opt/zookeeper/conf \
      --client_port=2181 \
      --election_port=3888 \
      --server_port=2888 \
      --tick_time=2000 \
      --init_limit=10 \
      --sync_limit=5 \
      --heap=512M \
      --max_client_cnxns=60 \
      --snap_retain_count=3 \
      --purge_interval=12 \
      --max_session_timeout=40000 \
      --min_session_timeout=4000 \
      --log_level=INFO"
    volumeMounts:
    - name: datadir
      mountPath: /var/lib/zookeeper
  volumes:
  - name: datadir
    persistentVolumeClaim:
      claimName: zk-data-0
---
apiVersion: v1
kind: Pod
metadata:
  name: zk-1
  labels:
    app: zk
spec:
  hostname: zk-1
  subdomain: zk-hs
  containers:
  - name: zk
    image: "registry.k8s.io/kubernetes-zookeeper:1.0-3.4.10"
    ports:
    - containerPort: 2181
      name: client
    - containerPort: 2888
      name: server
    - containerPort: 3888
      name: leader-election
    command:
    - sh
    - -c
    - "start-zookeeper \
      --servers=3 \
      --data_dir=/var/lib/zookeeper/data \
      --data_log_dir=/var/lib/zookeeper/data/log \
      --conf_dir=/opt/zookeeper/conf \
      --client_port=2181 \
      --election_port=3888 \
      --server_port=2888 \
      --tick_time=2000 \
      --init_limit=10 \
      --sync_limit=5 \
      --heap=512M \
      --max_client_cnxns=60 \
      --snap_retain_count=3 \
      --purge_interval=12 \
      --max_session_timeout=40000 \
      --min_session_timeout=4000 \
      --log_level=INFO"
    volumeMounts:
    - name: datadir
      mountPath: /var/lib/zookeeper
  volumes:
  - name: datadir
    persistentVolumeClaim:
      claimName: zk-data-1
---
apiVersion: v1
kind: Pod
metadata:
  name: zk-2
  labels:
    app: zk
spec:
  hostname: zk-2
  subdomain: zk-hs
  containers:
  - name: zk
    image: "registry.k8s.io/kubernetes-zookeeper:1.0-3.4.10"
    ports:
    - containerPort: 2181
      name: client
    - containerPort: 2888
      name: server
    - containerPort: 3888
      name: leader-election
    command:
    - sh
    - -c
    - "start-zookeeper \
      --servers=3 \
      --data_dir=/var/lib/zookeeper/data \
      --data_log_dir=/var/lib/zookeeper/data/log \
      --conf_dir=/opt/zookeeper/conf \
      --client_port=2181 \
      --election_port=3888 \
      --server_port=2888 \
      --tick_time=2000 \
      --init_limit=10 \
      --sync_limit=5 \
      --heap=512M \
      --max_client_cnxns=60 \
      --snap_retain_count=3 \
      --purge_interval=12 \
      --max_session_timeout=40000 \
      --min_session_timeout=4000 \
      --log_level=INFO"
    volumeMounts:
    - name: datadir
      mountPath: /var/lib/zookeeper
  volumes:
  - name: datadir
    persistentVolumeClaim:
      claimName: zk-data-2